### ISSUE TITLE
Compiled builds?

### ISSUE THREAD

**Issue by ghost** [antagon/TCHunt-ng#6]
Could you please provide compiled builds ready for use? At least a Windows `.exe` version should not be that difficult.

Many thanks in advance!

**Comment by antagon** [comment]
Hi @Mynvo your question is two-fold. First TCHunt-ng was build with POSIX compliant OSs in mind, Windows is not one of them. I believe that with some level of work and dedication you will be able to build it, but that's something you have to attempt to do yourself.

As for providing compiled binaries. I am against doing so as running a binary fetched from the Internet may potentially be a risk. Better approach would be to have packages for different distros, but since you asked about binaries for Windows, this is probably of no interest for you.

**Comment by ghost** [comment]
Thanks for your detailed reply.

I can run TCHunt-ng in a Linux machine, just thought I'll save time with a ready to go solution similar to the original TCHunt.
